networks:
  userservice-network:
    driver: bridge

services:
  userservice-mariadb:
    image: mariadb
    container_name: userservice-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: rootpw
      MARIADB_DATABASE: mydb
      MARIADB_USER: myuser
      MARIADB_PASSWORD: mypassword
    ports:
      - "3307:3306"
    volumes:
      - MariaDB_V:/var/lib/mysql
    networks:
      - userservice-network

  userservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: userservice-container
    ports:
      - "127.0.0.1:8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://userservice-mariadb:3306/mydb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    depends_on:
      - userservice-mariadb
    networks:
      - userservice-network
volumes:
  MariaDB_V: