networks:
  book-network:
    driver: bridge


services:
  bookrentalservicemariadb:
    image: mariadb
    container_name: bookrentalservice-mariadb
    ports:
      - "bookrentalservice:3307"
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: book_rental_service_db
      MARIADB_USER: book_rental_service_user
      MARIADB_PASSWORD: book_rental_service_super_secret
    volumes:
      - ./docker_data/mariadb:/var/lib/mysql
    networks:
      - book-network
    restart: unless-stopped

  bookrentalservice:
    build:
      context: "."
      dockerfile: Dockerfile
    image: bookrentalservice:latest
    container_name: bookrentalservicecontainer
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3307/book_rental_service_db
      SPRING_DATASOURCE_USERNAME: book_rental_service_user
      SPRING_DATASOURCE_PASSWORD: book_rental_service_super_secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - bookrentalservicemariadb
    networks:
      - book-network
    restart: unless-stopped

