networks:
  book-network:
    driver: bridge


services:
  bookservicemariadb:
    image: mariadb
    container_name: bookservice-mariadb
    ports:
      - "bookservice:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: book_service_db
      MARIADB_USER: book_service_user
      MARIADB_PASSWORD: book_service_super_secret
    volumes:
      - ./docker_data/mariadb:/var/lib/mysql
    networks:
      - book-network
    restart: unless-stopped

  bookservice:
    build:
      context: "."
      dockerfile: Dockerfile
    image: bookservice:latest
    container_name: bookservicecontainer
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/book_service_db
      SPRING_DATASOURCE_USERNAME: book_service_user
      SPRING_DATASOURCE_PASSWORD: book_service_super_secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - bookservicemariadb
    networks:
      - book-network
    restart: unless-stopped

